// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(cdk_ffiFFI)
import cdk_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cdk_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cdk_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol FfiLocalStoreProtocol : AnyObject {
    
}

open class FfiLocalStore:
    FfiLocalStoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_cdk_ffi_fn_clone_ffilocalstore(self.pointer, $0) }
    }
public convenience init()throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_constructor_ffilocalstore_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_cdk_ffi_fn_free_ffilocalstore(pointer, $0) }
    }

    
public static func newWithPath(dbPath: String?)throws  -> FfiLocalStore {
    return try  FfiConverterTypeFFILocalStore.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_constructor_ffilocalstore_new_with_path(
        FfiConverterOptionString.lower(dbPath),$0
    )
})
}
    

    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFILocalStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiLocalStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiLocalStore {
        return FfiLocalStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiLocalStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiLocalStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiLocalStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFILocalStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiLocalStore {
    return try FfiConverterTypeFFILocalStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFILocalStore_lower(_ value: FfiLocalStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFFILocalStore.lower(value)
}




public protocol FfiWalletProtocol : AnyObject {
    
    func balance() throws  -> FfiAmount
    
    /**
     * Fetch and initialize mint information
     * This should be called after wallet creation to set up the mint in the database
     */
    func getMintInfo() throws  -> String
    
    /**
     * Execute a melt operation (pay Lightning invoice)
     */
    func melt(quoteId: String) throws  -> FfiMelted
    
    /**
     * Create a melt quote for paying a Lightning invoice
     */
    func meltQuote(request: String) throws  -> FfiMeltQuote
    
    func mint(quoteId: String, splitTarget: FfiSplitTarget) throws  -> FfiAmount
    
    func mintQuote(amount: FfiAmount, description: String?) throws  -> FfiMintQuote
    
    func mintQuoteState(quoteId: String) throws  -> FfiMintQuoteBolt11Response
    
    func mintUrl()  -> String
    
    func prepareSend(amount: FfiAmount, options: FfiSendOptions) throws  -> FfiPreparedSend
    
    func send(amount: FfiAmount, options: FfiSendOptions, memo: FfiSendMemo?) throws  -> FfiToken
    
    func unit()  -> String
    
}

open class FfiWallet:
    FfiWalletProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_cdk_ffi_fn_clone_ffiwallet(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_cdk_ffi_fn_free_ffiwallet(pointer, $0) }
    }

    
public static func fromMnemonic(mintUrl: String, unit: FfiCurrencyUnit, localstore: FfiLocalStore, mnemonicWords: String)throws  -> FfiWallet {
    return try  FfiConverterTypeFFIWallet.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_constructor_ffiwallet_from_mnemonic(
        FfiConverterString.lower(mintUrl),
        FfiConverterTypeFFICurrencyUnit.lower(unit),
        FfiConverterTypeFFILocalStore.lower(localstore),
        FfiConverterString.lower(mnemonicWords),$0
    )
})
}
    
public static func restoreFromMnemonic(mintUrl: String, unit: FfiCurrencyUnit, localstore: FfiLocalStore, mnemonicWords: String)throws  -> FfiWallet {
    return try  FfiConverterTypeFFIWallet.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_constructor_ffiwallet_restore_from_mnemonic(
        FfiConverterString.lower(mintUrl),
        FfiConverterTypeFFICurrencyUnit.lower(unit),
        FfiConverterTypeFFILocalStore.lower(localstore),
        FfiConverterString.lower(mnemonicWords),$0
    )
})
}
    

    
open func balance()throws  -> FfiAmount {
    return try  FfiConverterTypeFFIAmount.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_balance(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Fetch and initialize mint information
     * This should be called after wallet creation to set up the mint in the database
     */
open func getMintInfo()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_get_mint_info(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Execute a melt operation (pay Lightning invoice)
     */
open func melt(quoteId: String)throws  -> FfiMelted {
    return try  FfiConverterTypeFFIMelted.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_melt(self.uniffiClonePointer(),
        FfiConverterString.lower(quoteId),$0
    )
})
}
    
    /**
     * Create a melt quote for paying a Lightning invoice
     */
open func meltQuote(request: String)throws  -> FfiMeltQuote {
    return try  FfiConverterTypeFFIMeltQuote.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_melt_quote(self.uniffiClonePointer(),
        FfiConverterString.lower(request),$0
    )
})
}
    
open func mint(quoteId: String, splitTarget: FfiSplitTarget)throws  -> FfiAmount {
    return try  FfiConverterTypeFFIAmount.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_mint(self.uniffiClonePointer(),
        FfiConverterString.lower(quoteId),
        FfiConverterTypeFFISplitTarget.lower(splitTarget),$0
    )
})
}
    
open func mintQuote(amount: FfiAmount, description: String?)throws  -> FfiMintQuote {
    return try  FfiConverterTypeFFIMintQuote.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote(self.uniffiClonePointer(),
        FfiConverterTypeFFIAmount.lower(amount),
        FfiConverterOptionString.lower(description),$0
    )
})
}
    
open func mintQuoteState(quoteId: String)throws  -> FfiMintQuoteBolt11Response {
    return try  FfiConverterTypeFFIMintQuoteBolt11Response.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote_state(self.uniffiClonePointer(),
        FfiConverterString.lower(quoteId),$0
    )
})
}
    
open func mintUrl() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_cdk_ffi_fn_method_ffiwallet_mint_url(self.uniffiClonePointer(),$0
    )
})
}
    
open func prepareSend(amount: FfiAmount, options: FfiSendOptions)throws  -> FfiPreparedSend {
    return try  FfiConverterTypeFFIPreparedSend.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_prepare_send(self.uniffiClonePointer(),
        FfiConverterTypeFFIAmount.lower(amount),
        FfiConverterTypeFFISendOptions.lower(options),$0
    )
})
}
    
open func send(amount: FfiAmount, options: FfiSendOptions, memo: FfiSendMemo?)throws  -> FfiToken {
    return try  FfiConverterTypeFFIToken.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_method_ffiwallet_send(self.uniffiClonePointer(),
        FfiConverterTypeFFIAmount.lower(amount),
        FfiConverterTypeFFISendOptions.lower(options),
        FfiConverterOptionTypeFFISendMemo.lower(memo),$0
    )
})
}
    
open func unit() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_cdk_ffi_fn_method_ffiwallet_unit(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIWallet: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiWallet

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiWallet {
        return FfiWallet(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiWallet) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiWallet {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiWallet, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIWallet_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiWallet {
    return try FfiConverterTypeFFIWallet.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIWallet_lower(_ value: FfiWallet) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFFIWallet.lower(value)
}


public struct FfiAmount {
    public var value: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: UInt64) {
        self.value = value
    }
}



extension FfiAmount: Equatable, Hashable {
    public static func ==(lhs: FfiAmount, rhs: FfiAmount) -> Bool {
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIAmount: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAmount {
        return
            try FfiAmount(
                value: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAmount, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIAmount_lift(_ buf: RustBuffer) throws -> FfiAmount {
    return try FfiConverterTypeFFIAmount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIAmount_lower(_ value: FfiAmount) -> RustBuffer {
    return FfiConverterTypeFFIAmount.lower(value)
}


public struct FfiMeltQuote {
    public var id: String
    public var unit: String
    public var amount: FfiAmount
    public var request: String
    public var feeReserve: FfiAmount
    public var expiry: UInt64
    public var paymentPreimage: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, unit: String, amount: FfiAmount, request: String, feeReserve: FfiAmount, expiry: UInt64, paymentPreimage: String?) {
        self.id = id
        self.unit = unit
        self.amount = amount
        self.request = request
        self.feeReserve = feeReserve
        self.expiry = expiry
        self.paymentPreimage = paymentPreimage
    }
}



extension FfiMeltQuote: Equatable, Hashable {
    public static func ==(lhs: FfiMeltQuote, rhs: FfiMeltQuote) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.unit != rhs.unit {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.request != rhs.request {
            return false
        }
        if lhs.feeReserve != rhs.feeReserve {
            return false
        }
        if lhs.expiry != rhs.expiry {
            return false
        }
        if lhs.paymentPreimage != rhs.paymentPreimage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(unit)
        hasher.combine(amount)
        hasher.combine(request)
        hasher.combine(feeReserve)
        hasher.combine(expiry)
        hasher.combine(paymentPreimage)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIMeltQuote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMeltQuote {
        return
            try FfiMeltQuote(
                id: FfiConverterString.read(from: &buf), 
                unit: FfiConverterString.read(from: &buf), 
                amount: FfiConverterTypeFFIAmount.read(from: &buf), 
                request: FfiConverterString.read(from: &buf), 
                feeReserve: FfiConverterTypeFFIAmount.read(from: &buf), 
                expiry: FfiConverterUInt64.read(from: &buf), 
                paymentPreimage: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMeltQuote, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.unit, into: &buf)
        FfiConverterTypeFFIAmount.write(value.amount, into: &buf)
        FfiConverterString.write(value.request, into: &buf)
        FfiConverterTypeFFIAmount.write(value.feeReserve, into: &buf)
        FfiConverterUInt64.write(value.expiry, into: &buf)
        FfiConverterOptionString.write(value.paymentPreimage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMeltQuote_lift(_ buf: RustBuffer) throws -> FfiMeltQuote {
    return try FfiConverterTypeFFIMeltQuote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMeltQuote_lower(_ value: FfiMeltQuote) -> RustBuffer {
    return FfiConverterTypeFFIMeltQuote.lower(value)
}


public struct FfiMelted {
    public var state: String
    public var preimage: String?
    public var amount: FfiAmount
    public var feePaid: FfiAmount

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: String, preimage: String?, amount: FfiAmount, feePaid: FfiAmount) {
        self.state = state
        self.preimage = preimage
        self.amount = amount
        self.feePaid = feePaid
    }
}



extension FfiMelted: Equatable, Hashable {
    public static func ==(lhs: FfiMelted, rhs: FfiMelted) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.preimage != rhs.preimage {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.feePaid != rhs.feePaid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(preimage)
        hasher.combine(amount)
        hasher.combine(feePaid)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIMelted: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMelted {
        return
            try FfiMelted(
                state: FfiConverterString.read(from: &buf), 
                preimage: FfiConverterOptionString.read(from: &buf), 
                amount: FfiConverterTypeFFIAmount.read(from: &buf), 
                feePaid: FfiConverterTypeFFIAmount.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMelted, into buf: inout [UInt8]) {
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterOptionString.write(value.preimage, into: &buf)
        FfiConverterTypeFFIAmount.write(value.amount, into: &buf)
        FfiConverterTypeFFIAmount.write(value.feePaid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMelted_lift(_ buf: RustBuffer) throws -> FfiMelted {
    return try FfiConverterTypeFFIMelted.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMelted_lower(_ value: FfiMelted) -> RustBuffer {
    return FfiConverterTypeFFIMelted.lower(value)
}


public struct FfiMintQuote {
    public var id: String
    public var mintUrl: String
    public var amount: FfiAmount
    public var unit: String
    public var request: String
    public var state: FfiMintQuoteState
    public var expiry: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, mintUrl: String, amount: FfiAmount, unit: String, request: String, state: FfiMintQuoteState, expiry: UInt64) {
        self.id = id
        self.mintUrl = mintUrl
        self.amount = amount
        self.unit = unit
        self.request = request
        self.state = state
        self.expiry = expiry
    }
}



extension FfiMintQuote: Equatable, Hashable {
    public static func ==(lhs: FfiMintQuote, rhs: FfiMintQuote) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.mintUrl != rhs.mintUrl {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.unit != rhs.unit {
            return false
        }
        if lhs.request != rhs.request {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.expiry != rhs.expiry {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(mintUrl)
        hasher.combine(amount)
        hasher.combine(unit)
        hasher.combine(request)
        hasher.combine(state)
        hasher.combine(expiry)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIMintQuote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMintQuote {
        return
            try FfiMintQuote(
                id: FfiConverterString.read(from: &buf), 
                mintUrl: FfiConverterString.read(from: &buf), 
                amount: FfiConverterTypeFFIAmount.read(from: &buf), 
                unit: FfiConverterString.read(from: &buf), 
                request: FfiConverterString.read(from: &buf), 
                state: FfiConverterTypeFFIMintQuoteState.read(from: &buf), 
                expiry: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMintQuote, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.mintUrl, into: &buf)
        FfiConverterTypeFFIAmount.write(value.amount, into: &buf)
        FfiConverterString.write(value.unit, into: &buf)
        FfiConverterString.write(value.request, into: &buf)
        FfiConverterTypeFFIMintQuoteState.write(value.state, into: &buf)
        FfiConverterUInt64.write(value.expiry, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuote_lift(_ buf: RustBuffer) throws -> FfiMintQuote {
    return try FfiConverterTypeFFIMintQuote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuote_lower(_ value: FfiMintQuote) -> RustBuffer {
    return FfiConverterTypeFFIMintQuote.lower(value)
}


public struct FfiMintQuoteBolt11Response {
    public var quote: String
    public var request: String
    public var state: FfiMintQuoteState
    public var expiry: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(quote: String, request: String, state: FfiMintQuoteState, expiry: UInt64?) {
        self.quote = quote
        self.request = request
        self.state = state
        self.expiry = expiry
    }
}



extension FfiMintQuoteBolt11Response: Equatable, Hashable {
    public static func ==(lhs: FfiMintQuoteBolt11Response, rhs: FfiMintQuoteBolt11Response) -> Bool {
        if lhs.quote != rhs.quote {
            return false
        }
        if lhs.request != rhs.request {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.expiry != rhs.expiry {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(quote)
        hasher.combine(request)
        hasher.combine(state)
        hasher.combine(expiry)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIMintQuoteBolt11Response: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMintQuoteBolt11Response {
        return
            try FfiMintQuoteBolt11Response(
                quote: FfiConverterString.read(from: &buf), 
                request: FfiConverterString.read(from: &buf), 
                state: FfiConverterTypeFFIMintQuoteState.read(from: &buf), 
                expiry: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMintQuoteBolt11Response, into buf: inout [UInt8]) {
        FfiConverterString.write(value.quote, into: &buf)
        FfiConverterString.write(value.request, into: &buf)
        FfiConverterTypeFFIMintQuoteState.write(value.state, into: &buf)
        FfiConverterOptionUInt64.write(value.expiry, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuoteBolt11Response_lift(_ buf: RustBuffer) throws -> FfiMintQuoteBolt11Response {
    return try FfiConverterTypeFFIMintQuoteBolt11Response.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuoteBolt11Response_lower(_ value: FfiMintQuoteBolt11Response) -> RustBuffer {
    return FfiConverterTypeFFIMintQuoteBolt11Response.lower(value)
}


public struct FfiPreparedSend {
    public var amount: FfiAmount
    public var swapFee: FfiAmount
    public var sendFee: FfiAmount
    public var totalFee: FfiAmount

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(amount: FfiAmount, swapFee: FfiAmount, sendFee: FfiAmount, totalFee: FfiAmount) {
        self.amount = amount
        self.swapFee = swapFee
        self.sendFee = sendFee
        self.totalFee = totalFee
    }
}



extension FfiPreparedSend: Equatable, Hashable {
    public static func ==(lhs: FfiPreparedSend, rhs: FfiPreparedSend) -> Bool {
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.swapFee != rhs.swapFee {
            return false
        }
        if lhs.sendFee != rhs.sendFee {
            return false
        }
        if lhs.totalFee != rhs.totalFee {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(amount)
        hasher.combine(swapFee)
        hasher.combine(sendFee)
        hasher.combine(totalFee)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIPreparedSend: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPreparedSend {
        return
            try FfiPreparedSend(
                amount: FfiConverterTypeFFIAmount.read(from: &buf), 
                swapFee: FfiConverterTypeFFIAmount.read(from: &buf), 
                sendFee: FfiConverterTypeFFIAmount.read(from: &buf), 
                totalFee: FfiConverterTypeFFIAmount.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPreparedSend, into buf: inout [UInt8]) {
        FfiConverterTypeFFIAmount.write(value.amount, into: &buf)
        FfiConverterTypeFFIAmount.write(value.swapFee, into: &buf)
        FfiConverterTypeFFIAmount.write(value.sendFee, into: &buf)
        FfiConverterTypeFFIAmount.write(value.totalFee, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIPreparedSend_lift(_ buf: RustBuffer) throws -> FfiPreparedSend {
    return try FfiConverterTypeFFIPreparedSend.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIPreparedSend_lower(_ value: FfiPreparedSend) -> RustBuffer {
    return FfiConverterTypeFFIPreparedSend.lower(value)
}


public struct FfiSendMemo {
    public var memo: String
    public var includeMemo: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(memo: String, includeMemo: Bool) {
        self.memo = memo
        self.includeMemo = includeMemo
    }
}



extension FfiSendMemo: Equatable, Hashable {
    public static func ==(lhs: FfiSendMemo, rhs: FfiSendMemo) -> Bool {
        if lhs.memo != rhs.memo {
            return false
        }
        if lhs.includeMemo != rhs.includeMemo {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(memo)
        hasher.combine(includeMemo)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFISendMemo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSendMemo {
        return
            try FfiSendMemo(
                memo: FfiConverterString.read(from: &buf), 
                includeMemo: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSendMemo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.memo, into: &buf)
        FfiConverterBool.write(value.includeMemo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendMemo_lift(_ buf: RustBuffer) throws -> FfiSendMemo {
    return try FfiConverterTypeFFISendMemo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendMemo_lower(_ value: FfiSendMemo) -> RustBuffer {
    return FfiConverterTypeFFISendMemo.lower(value)
}


public struct FfiSendOptions {
    public var memo: FfiSendMemo?
    public var amountSplitTarget: FfiSplitTarget
    public var sendKind: FfiSendKind
    public var includeFee: Bool
    public var metadata: [String: String]
    public var maxProofs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(memo: FfiSendMemo?, amountSplitTarget: FfiSplitTarget, sendKind: FfiSendKind, includeFee: Bool, metadata: [String: String], maxProofs: UInt64?) {
        self.memo = memo
        self.amountSplitTarget = amountSplitTarget
        self.sendKind = sendKind
        self.includeFee = includeFee
        self.metadata = metadata
        self.maxProofs = maxProofs
    }
}



extension FfiSendOptions: Equatable, Hashable {
    public static func ==(lhs: FfiSendOptions, rhs: FfiSendOptions) -> Bool {
        if lhs.memo != rhs.memo {
            return false
        }
        if lhs.amountSplitTarget != rhs.amountSplitTarget {
            return false
        }
        if lhs.sendKind != rhs.sendKind {
            return false
        }
        if lhs.includeFee != rhs.includeFee {
            return false
        }
        if lhs.metadata != rhs.metadata {
            return false
        }
        if lhs.maxProofs != rhs.maxProofs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(memo)
        hasher.combine(amountSplitTarget)
        hasher.combine(sendKind)
        hasher.combine(includeFee)
        hasher.combine(metadata)
        hasher.combine(maxProofs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFISendOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSendOptions {
        return
            try FfiSendOptions(
                memo: FfiConverterOptionTypeFFISendMemo.read(from: &buf), 
                amountSplitTarget: FfiConverterTypeFFISplitTarget.read(from: &buf), 
                sendKind: FfiConverterTypeFFISendKind.read(from: &buf), 
                includeFee: FfiConverterBool.read(from: &buf), 
                metadata: FfiConverterDictionaryStringString.read(from: &buf), 
                maxProofs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSendOptions, into buf: inout [UInt8]) {
        FfiConverterOptionTypeFFISendMemo.write(value.memo, into: &buf)
        FfiConverterTypeFFISplitTarget.write(value.amountSplitTarget, into: &buf)
        FfiConverterTypeFFISendKind.write(value.sendKind, into: &buf)
        FfiConverterBool.write(value.includeFee, into: &buf)
        FfiConverterDictionaryStringString.write(value.metadata, into: &buf)
        FfiConverterOptionUInt64.write(value.maxProofs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendOptions_lift(_ buf: RustBuffer) throws -> FfiSendOptions {
    return try FfiConverterTypeFFISendOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendOptions_lower(_ value: FfiSendOptions) -> RustBuffer {
    return FfiConverterTypeFFISendOptions.lower(value)
}


public struct FfiToken {
    public var tokenString: String
    public var mint: String
    public var memo: String?
    public var unit: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tokenString: String, mint: String, memo: String?, unit: String) {
        self.tokenString = tokenString
        self.mint = mint
        self.memo = memo
        self.unit = unit
    }
}



extension FfiToken: Equatable, Hashable {
    public static func ==(lhs: FfiToken, rhs: FfiToken) -> Bool {
        if lhs.tokenString != rhs.tokenString {
            return false
        }
        if lhs.mint != rhs.mint {
            return false
        }
        if lhs.memo != rhs.memo {
            return false
        }
        if lhs.unit != rhs.unit {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tokenString)
        hasher.combine(mint)
        hasher.combine(memo)
        hasher.combine(unit)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIToken: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiToken {
        return
            try FfiToken(
                tokenString: FfiConverterString.read(from: &buf), 
                mint: FfiConverterString.read(from: &buf), 
                memo: FfiConverterOptionString.read(from: &buf), 
                unit: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiToken, into buf: inout [UInt8]) {
        FfiConverterString.write(value.tokenString, into: &buf)
        FfiConverterString.write(value.mint, into: &buf)
        FfiConverterOptionString.write(value.memo, into: &buf)
        FfiConverterString.write(value.unit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIToken_lift(_ buf: RustBuffer) throws -> FfiToken {
    return try FfiConverterTypeFFIToken.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIToken_lower(_ value: FfiToken) -> RustBuffer {
    return FfiConverterTypeFFIToken.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCurrencyUnit {
    
    case sat
    case msat
    case usd
    case eur
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFICurrencyUnit: FfiConverterRustBuffer {
    typealias SwiftType = FfiCurrencyUnit

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCurrencyUnit {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sat
        
        case 2: return .msat
        
        case 3: return .usd
        
        case 4: return .eur
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCurrencyUnit, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sat:
            writeInt(&buf, Int32(1))
        
        
        case .msat:
            writeInt(&buf, Int32(2))
        
        
        case .usd:
            writeInt(&buf, Int32(3))
        
        
        case .eur:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFICurrencyUnit_lift(_ buf: RustBuffer) throws -> FfiCurrencyUnit {
    return try FfiConverterTypeFFICurrencyUnit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFICurrencyUnit_lower(_ value: FfiCurrencyUnit) -> RustBuffer {
    return FfiConverterTypeFFICurrencyUnit.lower(value)
}



extension FfiCurrencyUnit: Equatable, Hashable {}




public enum FfiError {

    
    
    case WalletError(msg: String
    )
    case InvalidInput(msg: String
    )
    case NetworkError(msg: String
    )
    case InternalError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .WalletError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .NetworkError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InternalError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .WalletError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NetworkError(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InternalError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiMintQuoteState {
    
    case unpaid
    case paid
    case issued
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFIMintQuoteState: FfiConverterRustBuffer {
    typealias SwiftType = FfiMintQuoteState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMintQuoteState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .unpaid
        
        case 2: return .paid
        
        case 3: return .issued
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiMintQuoteState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .unpaid:
            writeInt(&buf, Int32(1))
        
        
        case .paid:
            writeInt(&buf, Int32(2))
        
        
        case .issued:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuoteState_lift(_ buf: RustBuffer) throws -> FfiMintQuoteState {
    return try FfiConverterTypeFFIMintQuoteState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFIMintQuoteState_lower(_ value: FfiMintQuoteState) -> RustBuffer {
    return FfiConverterTypeFFIMintQuoteState.lower(value)
}



extension FfiMintQuoteState: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiSendKind {
    
    case onlineExact
    case onlineTolerance(tolerance: FfiAmount
    )
    case offlineExact
    case offlineTolerance(tolerance: FfiAmount
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFISendKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiSendKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSendKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .onlineExact
        
        case 2: return .onlineTolerance(tolerance: try FfiConverterTypeFFIAmount.read(from: &buf)
        )
        
        case 3: return .offlineExact
        
        case 4: return .offlineTolerance(tolerance: try FfiConverterTypeFFIAmount.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSendKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .onlineExact:
            writeInt(&buf, Int32(1))
        
        
        case let .onlineTolerance(tolerance):
            writeInt(&buf, Int32(2))
            FfiConverterTypeFFIAmount.write(tolerance, into: &buf)
            
        
        case .offlineExact:
            writeInt(&buf, Int32(3))
        
        
        case let .offlineTolerance(tolerance):
            writeInt(&buf, Int32(4))
            FfiConverterTypeFFIAmount.write(tolerance, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendKind_lift(_ buf: RustBuffer) throws -> FfiSendKind {
    return try FfiConverterTypeFFISendKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISendKind_lower(_ value: FfiSendKind) -> RustBuffer {
    return FfiConverterTypeFFISendKind.lower(value)
}



extension FfiSendKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiSplitTarget {
    
    case none
    case `default`
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFFISplitTarget: FfiConverterRustBuffer {
    typealias SwiftType = FfiSplitTarget

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSplitTarget {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .`default`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSplitTarget, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .`default`:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISplitTarget_lift(_ buf: RustBuffer) throws -> FfiSplitTarget {
    return try FfiConverterTypeFFISplitTarget.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFFISplitTarget_lower(_ value: FfiSplitTarget) -> RustBuffer {
    return FfiConverterTypeFFISplitTarget.lower(value)
}



extension FfiSplitTarget: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFFISendMemo: FfiConverterRustBuffer {
    typealias SwiftType = FfiSendMemo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFFISendMemo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFFISendMemo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Generate a 12-word mnemonic phrase
 */
public func generateMnemonic()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFFIError.lift) {
    uniffi_cdk_ffi_fn_func_generate_mnemonic($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cdk_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cdk_ffi_checksum_func_generate_mnemonic() != 44815) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_balance() != 40463) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_get_mint_info() != 13159) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_melt() != 3275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_melt_quote() != 39876) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_mint() != 58480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote() != 42885) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote_state() != 60165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_mint_url() != 18647) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_prepare_send() != 46706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_send() != 15473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_method_ffiwallet_unit() != 4593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new() != 15364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new_with_path() != 766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_constructor_ffiwallet_from_mnemonic() != 63545) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cdk_ffi_checksum_constructor_ffiwallet_restore_from_mnemonic() != 38466) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all