

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_cdk_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_cdk_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_cdk_ffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("cdk_ffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 26
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_cdk_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_cdk_ffi_checksum_func_generate_mnemonic() != 44815:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_balance() != 40463:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_get_mint_info() != 13159:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt() != 3275:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt_quote() != 39876:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint() != 58480:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote() != 42885:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote_state() != 60165:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_url() != 18647:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_prepare_send() != 46706:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_send() != 15473:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_method_ffiwallet_unit() != 4593:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new() != 15364:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new_with_path() != 766:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_from_mnemonic() != 63545:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_restore_from_mnemonic() != 38466:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UniffiLib.uniffi_cdk_ffi_fn_clone_ffilocalstore.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_clone_ffilocalstore.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_free_ffilocalstore.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_free_ffilocalstore.restype = None
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new_with_path.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new_with_path.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_clone_ffiwallet.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_clone_ffiwallet.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_free_ffiwallet.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_free_ffiwallet.restype = None
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_from_mnemonic.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_from_mnemonic.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_restore_from_mnemonic.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_restore_from_mnemonic.restype = ctypes.c_void_p
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_balance.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_balance.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_get_mint_info.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_get_mint_info.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt_quote.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt_quote.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote_state.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote_state.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_url.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_url.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_prepare_send.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_prepare_send.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_send.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_send.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_unit.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_unit.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cdk_ffi_fn_func_generate_mnemonic.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cdk_ffi_fn_func_generate_mnemonic.restype = _UniffiRustBuffer
_UniffiLib.ffi_cdk_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_cdk_ffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_cdk_ffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rustbuffer_free.restype = None
_UniffiLib.ffi_cdk_ffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_cdk_ffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_cdk_ffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_cdk_ffi_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_pointer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_cdk_ffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_cdk_ffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cdk_ffi_rust_future_free_void.restype = None
_UniffiLib.ffi_cdk_ffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cdk_ffi_rust_future_complete_void.restype = None
_UniffiLib.uniffi_cdk_ffi_checksum_func_generate_mnemonic.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_func_generate_mnemonic.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_balance.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_balance.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_get_mint_info.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_get_mint_info.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt_quote.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_melt_quote.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote_state.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_quote_state.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_url.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_mint_url.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_prepare_send.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_prepare_send.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_send.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_send.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_unit.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_method_ffiwallet_unit.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new_with_path.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffilocalstore_new_with_path.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_from_mnemonic.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_from_mnemonic.restype = ctypes.c_uint16
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_restore_from_mnemonic.argtypes = (
)
_UniffiLib.uniffi_cdk_ffi_checksum_constructor_ffiwallet_restore_from_mnemonic.restype = ctypes.c_uint16
_UniffiLib.ffi_cdk_ffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_cdk_ffi_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterBool:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



class FfiLocalStoreProtocol(typing.Protocol):
    pass


class FfiLocalStore:
    _pointer: ctypes.c_void_p
    def __init__(self, ):
        self._pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new,)

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_free_ffilocalstore, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_clone_ffilocalstore, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst
    @classmethod
    def new_with_path(cls, db_path: "typing.Optional[str]"):
        _UniffiConverterOptionalString.check_lower(db_path)
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffilocalstore_new_with_path,
        _UniffiConverterOptionalString.lower(db_path))
        return cls._make_instance_(pointer)




class _UniffiConverterTypeFfiLocalStore:

    @staticmethod
    def lift(value: int):
        return FfiLocalStore._make_instance_(value)

    @staticmethod
    def check_lower(value: FfiLocalStore):
        if not isinstance(value, FfiLocalStore):
            raise TypeError("Expected FfiLocalStore instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: FfiLocalStoreProtocol):
        if not isinstance(value, FfiLocalStore):
            raise TypeError("Expected FfiLocalStore instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: FfiLocalStoreProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))



class FfiWalletProtocol(typing.Protocol):
    def balance(self, ):
        raise NotImplementedError
    def get_mint_info(self, ):
        """
        Fetch and initialize mint information
        This should be called after wallet creation to set up the mint in the database
        """

        raise NotImplementedError
    def melt(self, quote_id: "str"):
        """
        Execute a melt operation (pay Lightning invoice)
        """

        raise NotImplementedError
    def melt_quote(self, request: "str"):
        """
        Create a melt quote for paying a Lightning invoice
        """

        raise NotImplementedError
    def mint(self, quote_id: "str",split_target: "FfiSplitTarget"):
        raise NotImplementedError
    def mint_quote(self, amount: "FfiAmount",description: "typing.Optional[str]"):
        raise NotImplementedError
    def mint_quote_state(self, quote_id: "str"):
        raise NotImplementedError
    def mint_url(self, ):
        raise NotImplementedError
    def prepare_send(self, amount: "FfiAmount",options: "FfiSendOptions"):
        raise NotImplementedError
    def send(self, amount: "FfiAmount",options: "FfiSendOptions",memo: "typing.Optional[FfiSendMemo]"):
        raise NotImplementedError
    def unit(self, ):
        raise NotImplementedError


class FfiWallet:
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_free_ffiwallet, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_clone_ffiwallet, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst
    @classmethod
    def from_mnemonic(cls, mint_url: "str",unit: "FfiCurrencyUnit",localstore: "FfiLocalStore",mnemonic_words: "str"):
        _UniffiConverterString.check_lower(mint_url)
        
        _UniffiConverterTypeFfiCurrencyUnit.check_lower(unit)
        
        _UniffiConverterTypeFfiLocalStore.check_lower(localstore)
        
        _UniffiConverterString.check_lower(mnemonic_words)
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_from_mnemonic,
        _UniffiConverterString.lower(mint_url),
        _UniffiConverterTypeFfiCurrencyUnit.lower(unit),
        _UniffiConverterTypeFfiLocalStore.lower(localstore),
        _UniffiConverterString.lower(mnemonic_words))
        return cls._make_instance_(pointer)

    @classmethod
    def restore_from_mnemonic(cls, mint_url: "str",unit: "FfiCurrencyUnit",localstore: "FfiLocalStore",mnemonic_words: "str"):
        _UniffiConverterString.check_lower(mint_url)
        
        _UniffiConverterTypeFfiCurrencyUnit.check_lower(unit)
        
        _UniffiConverterTypeFfiLocalStore.check_lower(localstore)
        
        _UniffiConverterString.check_lower(mnemonic_words)
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_constructor_ffiwallet_restore_from_mnemonic,
        _UniffiConverterString.lower(mint_url),
        _UniffiConverterTypeFfiCurrencyUnit.lower(unit),
        _UniffiConverterTypeFfiLocalStore.lower(localstore),
        _UniffiConverterString.lower(mnemonic_words))
        return cls._make_instance_(pointer)



    def balance(self, ) -> "FfiAmount":
        return _UniffiConverterTypeFfiAmount.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_balance,self._uniffi_clone_pointer(),)
        )





    def get_mint_info(self, ) -> "str":
        """
        Fetch and initialize mint information
        This should be called after wallet creation to set up the mint in the database
        """

        return _UniffiConverterString.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_get_mint_info,self._uniffi_clone_pointer(),)
        )





    def melt(self, quote_id: "str") -> "FfiMelted":
        """
        Execute a melt operation (pay Lightning invoice)
        """

        _UniffiConverterString.check_lower(quote_id)
        
        return _UniffiConverterTypeFfiMelted.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(quote_id))
        )





    def melt_quote(self, request: "str") -> "FfiMeltQuote":
        """
        Create a melt quote for paying a Lightning invoice
        """

        _UniffiConverterString.check_lower(request)
        
        return _UniffiConverterTypeFfiMeltQuote.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_melt_quote,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(request))
        )





    def mint(self, quote_id: "str",split_target: "FfiSplitTarget") -> "FfiAmount":
        _UniffiConverterString.check_lower(quote_id)
        
        _UniffiConverterTypeFfiSplitTarget.check_lower(split_target)
        
        return _UniffiConverterTypeFfiAmount.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(quote_id),
        _UniffiConverterTypeFfiSplitTarget.lower(split_target))
        )





    def mint_quote(self, amount: "FfiAmount",description: "typing.Optional[str]") -> "FfiMintQuote":
        _UniffiConverterTypeFfiAmount.check_lower(amount)
        
        _UniffiConverterOptionalString.check_lower(description)
        
        return _UniffiConverterTypeFfiMintQuote.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote,self._uniffi_clone_pointer(),
        _UniffiConverterTypeFfiAmount.lower(amount),
        _UniffiConverterOptionalString.lower(description))
        )





    def mint_quote_state(self, quote_id: "str") -> "FfiMintQuoteBolt11Response":
        _UniffiConverterString.check_lower(quote_id)
        
        return _UniffiConverterTypeFfiMintQuoteBolt11Response.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_quote_state,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(quote_id))
        )





    def mint_url(self, ) -> "str":
        return _UniffiConverterString.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_mint_url,self._uniffi_clone_pointer(),)
        )





    def prepare_send(self, amount: "FfiAmount",options: "FfiSendOptions") -> "FfiPreparedSend":
        _UniffiConverterTypeFfiAmount.check_lower(amount)
        
        _UniffiConverterTypeFfiSendOptions.check_lower(options)
        
        return _UniffiConverterTypeFfiPreparedSend.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_prepare_send,self._uniffi_clone_pointer(),
        _UniffiConverterTypeFfiAmount.lower(amount),
        _UniffiConverterTypeFfiSendOptions.lower(options))
        )





    def send(self, amount: "FfiAmount",options: "FfiSendOptions",memo: "typing.Optional[FfiSendMemo]") -> "FfiToken":
        _UniffiConverterTypeFfiAmount.check_lower(amount)
        
        _UniffiConverterTypeFfiSendOptions.check_lower(options)
        
        _UniffiConverterOptionalTypeFfiSendMemo.check_lower(memo)
        
        return _UniffiConverterTypeFfiToken.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_send,self._uniffi_clone_pointer(),
        _UniffiConverterTypeFfiAmount.lower(amount),
        _UniffiConverterTypeFfiSendOptions.lower(options),
        _UniffiConverterOptionalTypeFfiSendMemo.lower(memo))
        )





    def unit(self, ) -> "str":
        return _UniffiConverterString.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_cdk_ffi_fn_method_ffiwallet_unit,self._uniffi_clone_pointer(),)
        )






class _UniffiConverterTypeFfiWallet:

    @staticmethod
    def lift(value: int):
        return FfiWallet._make_instance_(value)

    @staticmethod
    def check_lower(value: FfiWallet):
        if not isinstance(value, FfiWallet):
            raise TypeError("Expected FfiWallet instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: FfiWalletProtocol):
        if not isinstance(value, FfiWallet):
            raise TypeError("Expected FfiWallet instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: FfiWalletProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class FfiAmount:
    value: "int"
    def __init__(self, *, value: "int"):
        self.value = value

    def __str__(self):
        return "FfiAmount(value={})".format(self.value)

    def __eq__(self, other):
        if self.value != other.value:
            return False
        return True

class _UniffiConverterTypeFfiAmount(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiAmount(
            value=_UniffiConverterUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt64.check_lower(value.value)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt64.write(value.value, buf)


class FfiMeltQuote:
    id: "str"
    unit: "str"
    amount: "FfiAmount"
    request: "str"
    fee_reserve: "FfiAmount"
    expiry: "int"
    payment_preimage: "typing.Optional[str]"
    def __init__(self, *, id: "str", unit: "str", amount: "FfiAmount", request: "str", fee_reserve: "FfiAmount", expiry: "int", payment_preimage: "typing.Optional[str]"):
        self.id = id
        self.unit = unit
        self.amount = amount
        self.request = request
        self.fee_reserve = fee_reserve
        self.expiry = expiry
        self.payment_preimage = payment_preimage

    def __str__(self):
        return "FfiMeltQuote(id={}, unit={}, amount={}, request={}, fee_reserve={}, expiry={}, payment_preimage={})".format(self.id, self.unit, self.amount, self.request, self.fee_reserve, self.expiry, self.payment_preimage)

    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.unit != other.unit:
            return False
        if self.amount != other.amount:
            return False
        if self.request != other.request:
            return False
        if self.fee_reserve != other.fee_reserve:
            return False
        if self.expiry != other.expiry:
            return False
        if self.payment_preimage != other.payment_preimage:
            return False
        return True

class _UniffiConverterTypeFfiMeltQuote(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiMeltQuote(
            id=_UniffiConverterString.read(buf),
            unit=_UniffiConverterString.read(buf),
            amount=_UniffiConverterTypeFfiAmount.read(buf),
            request=_UniffiConverterString.read(buf),
            fee_reserve=_UniffiConverterTypeFfiAmount.read(buf),
            expiry=_UniffiConverterUInt64.read(buf),
            payment_preimage=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.id)
        _UniffiConverterString.check_lower(value.unit)
        _UniffiConverterTypeFfiAmount.check_lower(value.amount)
        _UniffiConverterString.check_lower(value.request)
        _UniffiConverterTypeFfiAmount.check_lower(value.fee_reserve)
        _UniffiConverterUInt64.check_lower(value.expiry)
        _UniffiConverterOptionalString.check_lower(value.payment_preimage)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.id, buf)
        _UniffiConverterString.write(value.unit, buf)
        _UniffiConverterTypeFfiAmount.write(value.amount, buf)
        _UniffiConverterString.write(value.request, buf)
        _UniffiConverterTypeFfiAmount.write(value.fee_reserve, buf)
        _UniffiConverterUInt64.write(value.expiry, buf)
        _UniffiConverterOptionalString.write(value.payment_preimage, buf)


class FfiMelted:
    state: "str"
    preimage: "typing.Optional[str]"
    amount: "FfiAmount"
    fee_paid: "FfiAmount"
    def __init__(self, *, state: "str", preimage: "typing.Optional[str]", amount: "FfiAmount", fee_paid: "FfiAmount"):
        self.state = state
        self.preimage = preimage
        self.amount = amount
        self.fee_paid = fee_paid

    def __str__(self):
        return "FfiMelted(state={}, preimage={}, amount={}, fee_paid={})".format(self.state, self.preimage, self.amount, self.fee_paid)

    def __eq__(self, other):
        if self.state != other.state:
            return False
        if self.preimage != other.preimage:
            return False
        if self.amount != other.amount:
            return False
        if self.fee_paid != other.fee_paid:
            return False
        return True

class _UniffiConverterTypeFfiMelted(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiMelted(
            state=_UniffiConverterString.read(buf),
            preimage=_UniffiConverterOptionalString.read(buf),
            amount=_UniffiConverterTypeFfiAmount.read(buf),
            fee_paid=_UniffiConverterTypeFfiAmount.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.state)
        _UniffiConverterOptionalString.check_lower(value.preimage)
        _UniffiConverterTypeFfiAmount.check_lower(value.amount)
        _UniffiConverterTypeFfiAmount.check_lower(value.fee_paid)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.state, buf)
        _UniffiConverterOptionalString.write(value.preimage, buf)
        _UniffiConverterTypeFfiAmount.write(value.amount, buf)
        _UniffiConverterTypeFfiAmount.write(value.fee_paid, buf)


class FfiMintQuote:
    id: "str"
    mint_url: "str"
    amount: "FfiAmount"
    unit: "str"
    request: "str"
    state: "FfiMintQuoteState"
    expiry: "int"
    def __init__(self, *, id: "str", mint_url: "str", amount: "FfiAmount", unit: "str", request: "str", state: "FfiMintQuoteState", expiry: "int"):
        self.id = id
        self.mint_url = mint_url
        self.amount = amount
        self.unit = unit
        self.request = request
        self.state = state
        self.expiry = expiry

    def __str__(self):
        return "FfiMintQuote(id={}, mint_url={}, amount={}, unit={}, request={}, state={}, expiry={})".format(self.id, self.mint_url, self.amount, self.unit, self.request, self.state, self.expiry)

    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.mint_url != other.mint_url:
            return False
        if self.amount != other.amount:
            return False
        if self.unit != other.unit:
            return False
        if self.request != other.request:
            return False
        if self.state != other.state:
            return False
        if self.expiry != other.expiry:
            return False
        return True

class _UniffiConverterTypeFfiMintQuote(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiMintQuote(
            id=_UniffiConverterString.read(buf),
            mint_url=_UniffiConverterString.read(buf),
            amount=_UniffiConverterTypeFfiAmount.read(buf),
            unit=_UniffiConverterString.read(buf),
            request=_UniffiConverterString.read(buf),
            state=_UniffiConverterTypeFfiMintQuoteState.read(buf),
            expiry=_UniffiConverterUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.id)
        _UniffiConverterString.check_lower(value.mint_url)
        _UniffiConverterTypeFfiAmount.check_lower(value.amount)
        _UniffiConverterString.check_lower(value.unit)
        _UniffiConverterString.check_lower(value.request)
        _UniffiConverterTypeFfiMintQuoteState.check_lower(value.state)
        _UniffiConverterUInt64.check_lower(value.expiry)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.id, buf)
        _UniffiConverterString.write(value.mint_url, buf)
        _UniffiConverterTypeFfiAmount.write(value.amount, buf)
        _UniffiConverterString.write(value.unit, buf)
        _UniffiConverterString.write(value.request, buf)
        _UniffiConverterTypeFfiMintQuoteState.write(value.state, buf)
        _UniffiConverterUInt64.write(value.expiry, buf)


class FfiMintQuoteBolt11Response:
    quote: "str"
    request: "str"
    state: "FfiMintQuoteState"
    expiry: "typing.Optional[int]"
    def __init__(self, *, quote: "str", request: "str", state: "FfiMintQuoteState", expiry: "typing.Optional[int]"):
        self.quote = quote
        self.request = request
        self.state = state
        self.expiry = expiry

    def __str__(self):
        return "FfiMintQuoteBolt11Response(quote={}, request={}, state={}, expiry={})".format(self.quote, self.request, self.state, self.expiry)

    def __eq__(self, other):
        if self.quote != other.quote:
            return False
        if self.request != other.request:
            return False
        if self.state != other.state:
            return False
        if self.expiry != other.expiry:
            return False
        return True

class _UniffiConverterTypeFfiMintQuoteBolt11Response(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiMintQuoteBolt11Response(
            quote=_UniffiConverterString.read(buf),
            request=_UniffiConverterString.read(buf),
            state=_UniffiConverterTypeFfiMintQuoteState.read(buf),
            expiry=_UniffiConverterOptionalUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.quote)
        _UniffiConverterString.check_lower(value.request)
        _UniffiConverterTypeFfiMintQuoteState.check_lower(value.state)
        _UniffiConverterOptionalUInt64.check_lower(value.expiry)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.quote, buf)
        _UniffiConverterString.write(value.request, buf)
        _UniffiConverterTypeFfiMintQuoteState.write(value.state, buf)
        _UniffiConverterOptionalUInt64.write(value.expiry, buf)


class FfiPreparedSend:
    amount: "FfiAmount"
    swap_fee: "FfiAmount"
    send_fee: "FfiAmount"
    total_fee: "FfiAmount"
    def __init__(self, *, amount: "FfiAmount", swap_fee: "FfiAmount", send_fee: "FfiAmount", total_fee: "FfiAmount"):
        self.amount = amount
        self.swap_fee = swap_fee
        self.send_fee = send_fee
        self.total_fee = total_fee

    def __str__(self):
        return "FfiPreparedSend(amount={}, swap_fee={}, send_fee={}, total_fee={})".format(self.amount, self.swap_fee, self.send_fee, self.total_fee)

    def __eq__(self, other):
        if self.amount != other.amount:
            return False
        if self.swap_fee != other.swap_fee:
            return False
        if self.send_fee != other.send_fee:
            return False
        if self.total_fee != other.total_fee:
            return False
        return True

class _UniffiConverterTypeFfiPreparedSend(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiPreparedSend(
            amount=_UniffiConverterTypeFfiAmount.read(buf),
            swap_fee=_UniffiConverterTypeFfiAmount.read(buf),
            send_fee=_UniffiConverterTypeFfiAmount.read(buf),
            total_fee=_UniffiConverterTypeFfiAmount.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypeFfiAmount.check_lower(value.amount)
        _UniffiConverterTypeFfiAmount.check_lower(value.swap_fee)
        _UniffiConverterTypeFfiAmount.check_lower(value.send_fee)
        _UniffiConverterTypeFfiAmount.check_lower(value.total_fee)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypeFfiAmount.write(value.amount, buf)
        _UniffiConverterTypeFfiAmount.write(value.swap_fee, buf)
        _UniffiConverterTypeFfiAmount.write(value.send_fee, buf)
        _UniffiConverterTypeFfiAmount.write(value.total_fee, buf)


class FfiSendMemo:
    memo: "str"
    include_memo: "bool"
    def __init__(self, *, memo: "str", include_memo: "bool"):
        self.memo = memo
        self.include_memo = include_memo

    def __str__(self):
        return "FfiSendMemo(memo={}, include_memo={})".format(self.memo, self.include_memo)

    def __eq__(self, other):
        if self.memo != other.memo:
            return False
        if self.include_memo != other.include_memo:
            return False
        return True

class _UniffiConverterTypeFfiSendMemo(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiSendMemo(
            memo=_UniffiConverterString.read(buf),
            include_memo=_UniffiConverterBool.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.memo)
        _UniffiConverterBool.check_lower(value.include_memo)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.memo, buf)
        _UniffiConverterBool.write(value.include_memo, buf)


class FfiSendOptions:
    memo: "typing.Optional[FfiSendMemo]"
    amount_split_target: "FfiSplitTarget"
    send_kind: "FfiSendKind"
    include_fee: "bool"
    metadata: "dict[str, str]"
    max_proofs: "typing.Optional[int]"
    def __init__(self, *, memo: "typing.Optional[FfiSendMemo]", amount_split_target: "FfiSplitTarget", send_kind: "FfiSendKind", include_fee: "bool", metadata: "dict[str, str]", max_proofs: "typing.Optional[int]"):
        self.memo = memo
        self.amount_split_target = amount_split_target
        self.send_kind = send_kind
        self.include_fee = include_fee
        self.metadata = metadata
        self.max_proofs = max_proofs

    def __str__(self):
        return "FfiSendOptions(memo={}, amount_split_target={}, send_kind={}, include_fee={}, metadata={}, max_proofs={})".format(self.memo, self.amount_split_target, self.send_kind, self.include_fee, self.metadata, self.max_proofs)

    def __eq__(self, other):
        if self.memo != other.memo:
            return False
        if self.amount_split_target != other.amount_split_target:
            return False
        if self.send_kind != other.send_kind:
            return False
        if self.include_fee != other.include_fee:
            return False
        if self.metadata != other.metadata:
            return False
        if self.max_proofs != other.max_proofs:
            return False
        return True

class _UniffiConverterTypeFfiSendOptions(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiSendOptions(
            memo=_UniffiConverterOptionalTypeFfiSendMemo.read(buf),
            amount_split_target=_UniffiConverterTypeFfiSplitTarget.read(buf),
            send_kind=_UniffiConverterTypeFfiSendKind.read(buf),
            include_fee=_UniffiConverterBool.read(buf),
            metadata=_UniffiConverterMapStringString.read(buf),
            max_proofs=_UniffiConverterOptionalUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterOptionalTypeFfiSendMemo.check_lower(value.memo)
        _UniffiConverterTypeFfiSplitTarget.check_lower(value.amount_split_target)
        _UniffiConverterTypeFfiSendKind.check_lower(value.send_kind)
        _UniffiConverterBool.check_lower(value.include_fee)
        _UniffiConverterMapStringString.check_lower(value.metadata)
        _UniffiConverterOptionalUInt64.check_lower(value.max_proofs)

    @staticmethod
    def write(value, buf):
        _UniffiConverterOptionalTypeFfiSendMemo.write(value.memo, buf)
        _UniffiConverterTypeFfiSplitTarget.write(value.amount_split_target, buf)
        _UniffiConverterTypeFfiSendKind.write(value.send_kind, buf)
        _UniffiConverterBool.write(value.include_fee, buf)
        _UniffiConverterMapStringString.write(value.metadata, buf)
        _UniffiConverterOptionalUInt64.write(value.max_proofs, buf)


class FfiToken:
    token_string: "str"
    mint: "str"
    memo: "typing.Optional[str]"
    unit: "str"
    def __init__(self, *, token_string: "str", mint: "str", memo: "typing.Optional[str]", unit: "str"):
        self.token_string = token_string
        self.mint = mint
        self.memo = memo
        self.unit = unit

    def __str__(self):
        return "FfiToken(token_string={}, mint={}, memo={}, unit={})".format(self.token_string, self.mint, self.memo, self.unit)

    def __eq__(self, other):
        if self.token_string != other.token_string:
            return False
        if self.mint != other.mint:
            return False
        if self.memo != other.memo:
            return False
        if self.unit != other.unit:
            return False
        return True

class _UniffiConverterTypeFfiToken(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiToken(
            token_string=_UniffiConverterString.read(buf),
            mint=_UniffiConverterString.read(buf),
            memo=_UniffiConverterOptionalString.read(buf),
            unit=_UniffiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.token_string)
        _UniffiConverterString.check_lower(value.mint)
        _UniffiConverterOptionalString.check_lower(value.memo)
        _UniffiConverterString.check_lower(value.unit)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.token_string, buf)
        _UniffiConverterString.write(value.mint, buf)
        _UniffiConverterOptionalString.write(value.memo, buf)
        _UniffiConverterString.write(value.unit, buf)





class FfiCurrencyUnit(enum.Enum):
    SAT = 0
    
    MSAT = 1
    
    USD = 2
    
    EUR = 3
    


class _UniffiConverterTypeFfiCurrencyUnit(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiCurrencyUnit.SAT
        if variant == 2:
            return FfiCurrencyUnit.MSAT
        if variant == 3:
            return FfiCurrencyUnit.USD
        if variant == 4:
            return FfiCurrencyUnit.EUR
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == FfiCurrencyUnit.SAT:
            return
        if value == FfiCurrencyUnit.MSAT:
            return
        if value == FfiCurrencyUnit.USD:
            return
        if value == FfiCurrencyUnit.EUR:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == FfiCurrencyUnit.SAT:
            buf.write_i32(1)
        if value == FfiCurrencyUnit.MSAT:
            buf.write_i32(2)
        if value == FfiCurrencyUnit.USD:
            buf.write_i32(3)
        if value == FfiCurrencyUnit.EUR:
            buf.write_i32(4)




# FfiError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class FfiError(Exception):
    pass

_UniffiTempFfiError = FfiError

class FfiError:  # type: ignore
    class WalletError(_UniffiTempFfiError):
        def __init__(self, msg):
            super().__init__(", ".join([
                "msg={!r}".format(msg),
            ]))
            self.msg = msg

        def __repr__(self):
            return "FfiError.WalletError({})".format(str(self))
    _UniffiTempFfiError.WalletError = WalletError # type: ignore
    class InvalidInput(_UniffiTempFfiError):
        def __init__(self, msg):
            super().__init__(", ".join([
                "msg={!r}".format(msg),
            ]))
            self.msg = msg

        def __repr__(self):
            return "FfiError.InvalidInput({})".format(str(self))
    _UniffiTempFfiError.InvalidInput = InvalidInput # type: ignore
    class NetworkError(_UniffiTempFfiError):
        def __init__(self, msg):
            super().__init__(", ".join([
                "msg={!r}".format(msg),
            ]))
            self.msg = msg

        def __repr__(self):
            return "FfiError.NetworkError({})".format(str(self))
    _UniffiTempFfiError.NetworkError = NetworkError # type: ignore
    class InternalError(_UniffiTempFfiError):
        def __init__(self, msg):
            super().__init__(", ".join([
                "msg={!r}".format(msg),
            ]))
            self.msg = msg

        def __repr__(self):
            return "FfiError.InternalError({})".format(str(self))
    _UniffiTempFfiError.InternalError = InternalError # type: ignore

FfiError = _UniffiTempFfiError # type: ignore
del _UniffiTempFfiError


class _UniffiConverterTypeFfiError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiError.WalletError(
                _UniffiConverterString.read(buf),
            )
        if variant == 2:
            return FfiError.InvalidInput(
                _UniffiConverterString.read(buf),
            )
        if variant == 3:
            return FfiError.NetworkError(
                _UniffiConverterString.read(buf),
            )
        if variant == 4:
            return FfiError.InternalError(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, FfiError.WalletError):
            _UniffiConverterString.check_lower(value.msg)
            return
        if isinstance(value, FfiError.InvalidInput):
            _UniffiConverterString.check_lower(value.msg)
            return
        if isinstance(value, FfiError.NetworkError):
            _UniffiConverterString.check_lower(value.msg)
            return
        if isinstance(value, FfiError.InternalError):
            _UniffiConverterString.check_lower(value.msg)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, FfiError.WalletError):
            buf.write_i32(1)
            _UniffiConverterString.write(value.msg, buf)
        if isinstance(value, FfiError.InvalidInput):
            buf.write_i32(2)
            _UniffiConverterString.write(value.msg, buf)
        if isinstance(value, FfiError.NetworkError):
            buf.write_i32(3)
            _UniffiConverterString.write(value.msg, buf)
        if isinstance(value, FfiError.InternalError):
            buf.write_i32(4)
            _UniffiConverterString.write(value.msg, buf)





class FfiMintQuoteState(enum.Enum):
    UNPAID = 0
    
    PAID = 1
    
    ISSUED = 2
    


class _UniffiConverterTypeFfiMintQuoteState(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiMintQuoteState.UNPAID
        if variant == 2:
            return FfiMintQuoteState.PAID
        if variant == 3:
            return FfiMintQuoteState.ISSUED
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == FfiMintQuoteState.UNPAID:
            return
        if value == FfiMintQuoteState.PAID:
            return
        if value == FfiMintQuoteState.ISSUED:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == FfiMintQuoteState.UNPAID:
            buf.write_i32(1)
        if value == FfiMintQuoteState.PAID:
            buf.write_i32(2)
        if value == FfiMintQuoteState.ISSUED:
            buf.write_i32(3)







class FfiSendKind:
    def __init__(self):
        raise RuntimeError("FfiSendKind cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    class ONLINE_EXACT:

        def __init__(self,):
            pass

        def __str__(self):
            return "FfiSendKind.ONLINE_EXACT()".format()

        def __eq__(self, other):
            if not other.is_online_exact():
                return False
            return True
    
    class ONLINE_TOLERANCE:
        tolerance: "FfiAmount"

        def __init__(self,tolerance: "FfiAmount"):
            self.tolerance = tolerance

        def __str__(self):
            return "FfiSendKind.ONLINE_TOLERANCE(tolerance={})".format(self.tolerance)

        def __eq__(self, other):
            if not other.is_online_tolerance():
                return False
            if self.tolerance != other.tolerance:
                return False
            return True
    
    class OFFLINE_EXACT:

        def __init__(self,):
            pass

        def __str__(self):
            return "FfiSendKind.OFFLINE_EXACT()".format()

        def __eq__(self, other):
            if not other.is_offline_exact():
                return False
            return True
    
    class OFFLINE_TOLERANCE:
        tolerance: "FfiAmount"

        def __init__(self,tolerance: "FfiAmount"):
            self.tolerance = tolerance

        def __str__(self):
            return "FfiSendKind.OFFLINE_TOLERANCE(tolerance={})".format(self.tolerance)

        def __eq__(self, other):
            if not other.is_offline_tolerance():
                return False
            if self.tolerance != other.tolerance:
                return False
            return True
    
    

    # For each variant, we have an `is_NAME` method for easily checking
    # whether an instance is that variant.
    def is_online_exact(self) -> bool:
        return isinstance(self, FfiSendKind.ONLINE_EXACT)
    def is_online_tolerance(self) -> bool:
        return isinstance(self, FfiSendKind.ONLINE_TOLERANCE)
    def is_offline_exact(self) -> bool:
        return isinstance(self, FfiSendKind.OFFLINE_EXACT)
    def is_offline_tolerance(self) -> bool:
        return isinstance(self, FfiSendKind.OFFLINE_TOLERANCE)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
FfiSendKind.ONLINE_EXACT = type("FfiSendKind.ONLINE_EXACT", (FfiSendKind.ONLINE_EXACT, FfiSendKind,), {})  # type: ignore
FfiSendKind.ONLINE_TOLERANCE = type("FfiSendKind.ONLINE_TOLERANCE", (FfiSendKind.ONLINE_TOLERANCE, FfiSendKind,), {})  # type: ignore
FfiSendKind.OFFLINE_EXACT = type("FfiSendKind.OFFLINE_EXACT", (FfiSendKind.OFFLINE_EXACT, FfiSendKind,), {})  # type: ignore
FfiSendKind.OFFLINE_TOLERANCE = type("FfiSendKind.OFFLINE_TOLERANCE", (FfiSendKind.OFFLINE_TOLERANCE, FfiSendKind,), {})  # type: ignore




class _UniffiConverterTypeFfiSendKind(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiSendKind.ONLINE_EXACT(
            )
        if variant == 2:
            return FfiSendKind.ONLINE_TOLERANCE(
                _UniffiConverterTypeFfiAmount.read(buf),
            )
        if variant == 3:
            return FfiSendKind.OFFLINE_EXACT(
            )
        if variant == 4:
            return FfiSendKind.OFFLINE_TOLERANCE(
                _UniffiConverterTypeFfiAmount.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_online_exact():
            return
        if value.is_online_tolerance():
            _UniffiConverterTypeFfiAmount.check_lower(value.tolerance)
            return
        if value.is_offline_exact():
            return
        if value.is_offline_tolerance():
            _UniffiConverterTypeFfiAmount.check_lower(value.tolerance)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_online_exact():
            buf.write_i32(1)
        if value.is_online_tolerance():
            buf.write_i32(2)
            _UniffiConverterTypeFfiAmount.write(value.tolerance, buf)
        if value.is_offline_exact():
            buf.write_i32(3)
        if value.is_offline_tolerance():
            buf.write_i32(4)
            _UniffiConverterTypeFfiAmount.write(value.tolerance, buf)







class FfiSplitTarget(enum.Enum):
    NONE = 0
    
    DEFAULT = 1
    


class _UniffiConverterTypeFfiSplitTarget(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiSplitTarget.NONE
        if variant == 2:
            return FfiSplitTarget.DEFAULT
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == FfiSplitTarget.NONE:
            return
        if value == FfiSplitTarget.DEFAULT:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == FfiSplitTarget.NONE:
            buf.write_i32(1)
        if value == FfiSplitTarget.DEFAULT:
            buf.write_i32(2)





class _UniffiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeFfiSendMemo(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeFfiSendMemo.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeFfiSendMemo.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeFfiSendMemo.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterMapStringString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, items):
        for (key, value) in items.items():
            _UniffiConverterString.check_lower(key)
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, items, buf):
        buf.write_i32(len(items))
        for (key, value) in items.items():
            _UniffiConverterString.write(key, buf)
            _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative map size")

        # It would be nice to use a dict comprehension,
        # but in Python 3.7 and before the evaluation order is not according to spec,
        # so we we're reading the value before the key.
        # This loop makes the order explicit: first reading the key, then the value.
        d = {}
        for i in range(count):
            key = _UniffiConverterString.read(buf)
            val = _UniffiConverterString.read(buf)
            d[key] = val
        return d

# Async support

def generate_mnemonic() -> "str":
    """
    Generate a 12-word mnemonic phrase
    """

    return _UniffiConverterString.lift(_uniffi_rust_call_with_error(_UniffiConverterTypeFfiError,_UniffiLib.uniffi_cdk_ffi_fn_func_generate_mnemonic,))


__all__ = [
    "InternalError",
    "FfiCurrencyUnit",
    "FfiError",
    "FfiMintQuoteState",
    "FfiSendKind",
    "FfiSplitTarget",
    "FfiAmount",
    "FfiMeltQuote",
    "FfiMelted",
    "FfiMintQuote",
    "FfiMintQuoteBolt11Response",
    "FfiPreparedSend",
    "FfiSendMemo",
    "FfiSendOptions",
    "FfiToken",
    "generate_mnemonic",
    "FfiLocalStore",
    "FfiWallet",
]

